Description: SageMaker notebook instance, S3 Bucket and IAM roles to be used for Lookout for Equipment Getting Started tutorial

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Join
        - "-"
        - - "lookoutequiment-getting-started"
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - "/"
                  - !Ref "AWS::StackId"

  SageMakerIamRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - sagemaker.amazonaws.com
                - lookoutequipment.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonSageMakerFullAccess"
        - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
        - "arn:aws:iam::aws:policy/IAMFullAccess"
        - "arn:aws:iam::aws:policy/AmazonLookoutEquipmentFullAccess"
      Path: /
      Policies:
        - PolicyName: LookoutForEquipment
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 'lookoutequipment:*'
                Resource: '*'
                Sid: "LookoutEquipmentAPIAccess"
              - Effect: Allow
                Action: 'iam:PassRole'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 's3:Get*'
                  - 's3:List*'
                  - 's3:PutObject'
                Resource: !Join
                  - ""
                  - - "arn:aws:s3:::"
                    - !Ref S3Bucket
                    - "*"
                Sid: TrainingAndLabelDataAccess

  NotebookInstance:
    Type: 'AWS::SageMaker::NotebookInstance'
    Properties:
      InstanceType: ml.t3.medium
      RoleArn: !GetAtt SageMakerIamRole.Arn
      NotebookInstanceName: !Join
        - "-"
        - - "lookout-equipment-getting-started"
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - "/"
                  - !Ref "AWS::StackId"

      VolumeSizeInGB: 5
      DefaultCodeRepository: 'https://github.com/aws-samples/amazon-lookout-for-equipment.git'

Outputs:
  NotebookInstanceId:
    Value: !Ref NotebookInstance
  S3Bucket:
    Value: !Ref S3Bucket
    Description: S3 Bucket for object storage